export const REQUEST_LOGIN = "REQUEST_LOGIN"
export const SUCCESS_LOGIN = "SUCCESS_LOGIN"
export const FAILURE_LOGIN = "FAILURE_LOGIN"

export const SET_PERSIST_PATH = "SET_PERSIST_PATH"
export const SET_MAIN_ERROR = "SET_MAIN_ERROR"

export const FETCH_TIMEOUT = "FETCH_TIMEOUT"
export const FETCH_ERROR = "FETCH_ERROR"

export const SESSION_CHECK = "SESSION_CHECK"
export const REQ_PUSH = "REQ_PUSH"


